services:
  - type: web
    name: shiplogsitic-12
    runtime: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    autoDeployTrigger: commit
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://shiplogsitic.onrender.com
